name: act-demo
run-name: act-demo-runing
on: [push]
jobs:
  job1:
    environment: GANG-EVN
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [10.x]
    env:
      OSS_ID: ${{ secrets.OSS_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "${{ secrets.OSS_ID }} = ${{ vars.HUAN_VAR }}"
      - run: npm install
      - run: npm run start
