name: act-demo
run-name: act-demo-runing
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      OSS_ID: ${{ secrets.OSS_ID }}
    steps:
      - run: echo "${{ secrets.OSS_ID }} = ${{ vars.HUAN_VAR }}"
      - run: npm install
      - run: npm run start
